### PR TITLE
test(JestMigration): convert XAxisSpec 

### PR DESCRIPTION
**Pull request by akib22**
## Description

Refactor `test/specs/cartesian/XAxisSpec.js` to `test-jest/cartesian/XAxis.spec.tsx`

## Related Issue

#3193 

## Types of changes

- [x] Jest Migration

## Checklist:

- [x] My code follows the code style of this project.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by akib22** [comment]
```ts
it('Render Bars with gap', () => {
  const wrapper = mount(
    <BarChart width={300} height={300} data={data}>
      <Bar dataKey="y" />
      <XAxis dataKey="x" type="number" domain={['dataMin', 'dataMax']} padding="gap" />
      <YAxis dataKey="y" />
    </BarChart>,
  );
  
  expect(parseInt(wrapper.find(Bar).prop('data')[0].x, 10)).to.equal(70);
});
```
In the above test case `gap` is used for `padding` property, but the documentation suggests using an object like  `{left: 10, right: 10}`. Then I used an object to rewrite this test but I am not able to find any way to assert that the gap is rendered to the chart. Do you have any suggestions for asserting this case @ckifer @niklaskallander?

**Comment by nikolasrieble** [comment]
Related https://github.com/recharts/recharts/pull/3225

**Comment by nikolasrieble** [comment]
Related https://github.com/recharts/recharts.org/issues/244

**Comment by proke03** [comment]
I solved this issue and made PR on your fork.

**Pull request closed without merging**
