### PR TITLE
getLegendProps does not compute payload

### PR DESCRIPTION
**Pull request by PavelVanecek**
## Description

Now that everything is in context we can stop passing payload via props.

## Related Issue

https://github.com/recharts/recharts/discussions/3717

## Motivation and Context

One less use of `formattedGraphicalItems` and one step closer to cloning the Legend.

## How Has This Been Tested?

npm test

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] I have added a storybook story or extended an existing story to show my changes
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by ckifer — APPROVED** [review]
Red has never looked so good

**Comment by ckifer** [comment]
@PavelVanecek starting here we had some visual diff in chromatic. My bad for not looking at it before

https://www.chromatic.com/build?appId=63da8268a0da9970db6992aa&number=693

Lots of chart margin shifts including an overlapping Legend

**Comment by PavelVanecek** [comment]
> @PavelVanecek starting here we had some visual diff in chromatic. My bad for not looking at it before
> 
> https://www.chromatic.com/build?appId=63da8268a0da9970db6992aa&number=693
> 
> Lots of chart margin shifts including an overlapping Legend

🤦 this is because `Legend` no longer reads `payload` at all, and so on payload change it does not re-render and therefore it does not trigger `getBoundingClientRect` and `onBBoxUpdate`.

How far from 3.x release are we? I am thinking if I should revert this change, or try to rethink the bounding box updates instead.

**Comment by ckifer** [comment]
I would say pretty far yet. I'd do what you need do!

**Pull request merged**
