### PR TITLE
Remove unused renderGraphicChild

### PR DESCRIPTION
**Pull request by PavelVanecek**
## Description

Unused code! Finally!

## Related Issue

https://github.com/recharts/recharts/issues/4583

### CODE REVIEW

**Comment by PavelVanecek** [comment]
OK it's not much as the rest is still used in the Tooltip generator. But it's something.

**Comment by ckifer** [comment]
🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉

**Comment by ckifer** [comment]
huge milestone though

**Review by ckifer — APPROVED** [review]

**Comment by ckifer** [comment]
Now when does that render map get removed

**Comment by PavelVanecek** [comment]
I'll do Customized next, then the map. Quite a few tests need an update.

**Pull request merged**
