### PR TITLE
fix(Line): onClick for activeDot is incorrectly typed

### PR DESCRIPTION
**Pull request by andrewangelle**
fix(Line): onClick for activeDot is incorrectly typed

## Description

Have `activeDot` include the type for `DotProps` which fixes the incorrect types for the event handlers that are added in [line 2036 in generateCategoricalChart](https://github.com/recharts/recharts/blob/master/src/chart/generateCategoricalChart.tsx#L2036
) which give a different payload to the callback mentioned in the issue.

## Related Issue

#3922 

## Motivation and Context

Fixes incorrect types that introduced a breaking change 

## How Has This Been Tested?
Manually. It's a purely typescript issue. Screenshot below.

## Screenshots (if appropriate):
Screenshot 2023-10-31 at 4 22 50 PM

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] I have added a storybook story or extended an existing story to show my changes
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by andrewangelle** [comment]
@ckifer I pulled down your v2.9.1 patch branch and cherry picked this commit into it locally to make sure there were no surprises there. I was able to run the tests/build/linter all successfully on my local with this commit.

**Review by nikolasrieble — APPROVED** [review]
🚀 Thank you. Can you please double check whether this issue also exists with other ActiveShape usage cases?

**Comment by andrewangelle** [comment]
@nikolasrieble  I console logged the events coming in from the onClick for the others and they are receiving a normal event payload that you'd expect from an svg element event handler which is consistent with the current type definition for those.

It'll take me a bit longer to track down if this is how they were typed prior to v2.9.0. 

This one for `activeDot` is different than the rest because the chart wrapper adds a different event handler and renders the active dots separately. The other use cases of `activeBar/activeShape` are handled via the same rendering method in the chart wrapper and don't have this same overwriting of the event.

**Review by ckifer — APPROVED** [review]

**Comment by ckifer** [comment]
Maybe a tiny bit late for this but `Area` also has an `activeDot` prop. That one however, does not use the new ActiveShape type

https://github.com/recharts/recharts/blob/master/src/cartesian/Area.tsx#L66

**Comment by andrewangelle** [comment]
For the components touched in the `ActiveShape` changes, the types for the event handlers all look to be equivalent in the latest version versus 2.8.0. Though admittedly, it's hard to anticipate every which way users could have been using that prop to anticipate other ways to test that haven't already been covered. I'll continue to think about this and see if I can find any inconsistencies that might have been missed.

**Comment by ckifer** [comment]
Yep agreed! Thank you. 

It's completely impossible to be honest - it's going to be tough to narrow types in minor version releases. Generally external facing type changes are breaking changes unfortunately

**Pull request merged**
