### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by Glitches**
Updating this package prevents triggering resizeObserver error

### CODE REVIEW

**Comment by Glitches** [comment]
sorry for my late reply.
The error is reported in thi issue: https://github.com/maslianok/react-resize-detector/issues/45
I have a list of data displayed with a modified pie chart and as soon as I resize the window, the error pops up. In production wouldn't have been a problem if Sentry didn't catch it, but we had to shut that error because it was catching a lot of them. 
So, the point is that the error is generate from that package and may affect other users, but is not really blocking. Just annoying

**Comment by dmr** [comment]
Does recharts still support react@15?

I would like to use recharts inside storybook and react-resize-detector has an issue which was fixed in 3.1.0 (https://github.com/maslianok/react-resize-detector/issues/34) --> What can I do to help this pull request getting merged?

**Comment by Glitches** [comment]
@dmr You could fork and pack recharts yourself, if you think is reasonable enough having a forked package.

**Comment by xile611** [comment]
We'll release a major version to only support react@16, then we'll update react-resize-detector ，thanks!

**Pull request closed without merging**
