### PR TITLE
Fixed package versions to be no longer dependent of old d3 packages

### LINKED ISSUE #3012: Fix dependency vulnerability d3-color < 3.1.0
- [ ] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Updating the package will, fix the Redos vulnerability of the d3-color; https://github.com/advisories/GHSA-36jr-mh4h-2g58

### What does the proposed API look like?
No api needed

### PR DESCRIPTION
**Pull request by mark-todd**
Resolves #3012 by increasing version number

Please note I have not tested the recharts codebase with these later versions (some of which are major version increases)

### CODE REVIEW

**Comment by mark-todd** [comment]
I have just found dependabot has already setup a PR for this #3009

**Review by iareintelligent — APPROVED** [review]
Yes please!

**Comment by herleraja** [comment]
@arcthur any chance this PR will be merged ? or #3009

**Comment by mark-todd** [comment]
@herleraja This ongoing discussion is very relevant to this PR https://github.com/recharts/recharts/issues/3012

**Comment by ckifer** [comment]
Hey @mark-todd, going to close this for now due to #3012. Will continue to discuss there and a new PR will be raised to safely increment package versions.

**Pull request closed without merging**
