### PR TITLE
fix: type check

### PR DESCRIPTION
**Pull request by HHongSeungWoo**
## Description

I should have checked if it's a boolean type, but I was converting the value to a boolean

## Related Issue

#3990 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] I have added a storybook story or extended an existing story to show my changes
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by ckifer** [comment]
This was using isBoolean previously?

Any other places in code that do this?

**Comment by HHongSeungWoo** [comment]
> This was using isBoolean previously?
> 
> Any other places in code that do this?

yes.

I can't check everything, but it's not in `generateCategoricalChart.tsx` at least

**Comment by ckifer** [comment]
Thanks 👍

**Comment by nikolasrieble** [comment]
Would it make sense to add a test to verify this does not break again?

**Comment by trainoasis** [comment]
I think this might have broken the `ReferenceArea` - it is now without grayish color as well, even when you define stroke or color prop. Can you check pls?

**Comment by HHongSeungWoo** [comment]
Could you please create an issue with a reproducible example??

**Comment by trainoasis** [comment]
@HHongSeungWoo investigated a bit more & seems this isn't related to your changes at all! It was a very hidden change on our side. Sorry for false alarm! 🙌🏼

**Pull request merged**
