### PR TITLE
fix: Tooltip sometimes re-appears after cursor leaves chart

### PR DESCRIPTION
**Pull request by HHongSeungWoo**
## Description

Cancel the throttled mousemove event when the mouseleave event is triggered

## Related Issue

#4093 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] I have added a storybook story or extended an existing story to show my changes
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by ckifer** [comment]
nice, thanks for the fix

**Review by ckifer — APPROVED** [review]

**Comment by PavelVanecek** [comment]
Unit tests would be great 🙃

**Comment by ckifer** [comment]
@HHongSeungWoo I think this may have broke https://github.com/recharts/recharts/issues/4424

**Comment by HHongSeungWoo** [comment]
@ckifer It seems there is an issue with the timing of measuring the size of the tooltip element. It appears to have been resolved in the 3.x branch; should we modify the master branch?

**Comment by ckifer** [comment]
Only if the fix is easy - otherwise we can wait until 3.0

Appreciate you looking, this was the only change I saw for tooltip between 2.11 and 2.12 but probably a different PR

**Comment by HHongSeungWoo** [comment]
It seems that the issue was caused by https://github.com/recharts/recharts/commit/830bd0040cd0554f0b252c1e2e3bb8c457668ae8 :cry:

**Pull request merged**
