### PR TITLE
fix: remove deprecated alwaysShow

### PR DESCRIPTION
**Pull request by proke03**
## Description
I deleted my fork and fork it again.
So I can't make additional commit to PR #3277.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by ckifer — APPROVED** [review]
Looks good, just merge master when you get a chance 🚀

**Review by nikolasrieble — APPROVED** [review]
Thank you!

**Comment by nikolasrieble** [comment]
Sorry, I mistakenly merged this. We have to wait for a major release, which we certainly do not want to do right now. Will revert. Would you like to reopen the PR? 🤦 🙏

**Comment by nikolasrieble** [comment]
Even further, the property is still used, thus this would actually change the behaviour of existing charts, see 

```
export const ifOverflowMatches = (props: any, value: string) => {
  const { alwaysShow } = props;
  let { ifOverflow } = props;

  if (alwaysShow) {
    ifOverflow = 'extendDomain';
  }

  return ifOverflow === value;
};

```

**Comment by ckifer** [comment]
+1, we can't merge this until we do a major release

**Pull request merged**
