### PR TITLE
Add formatter optional prop to LabelList type definition

### LINKED ISSUE #2472: Missing Type definition for `formatter` in LabelList
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[Edit on CodeSandbox](https://codesandbox.io/s/label-list-missing-type-formatter-c6rfw)

### Steps to reproduce
Use `formatter` prop on LabelList in Typescript.

### What is expected?
No Type error

### What is actually happening?
Type error

| Environment | Info |
|---|---|
| Recharts | v2.0.8 |
| React | 17.0.1 |
| System | Codesandbox |
| Browser | Codesandbox |

### PR DESCRIPTION
**Pull request by bsell93**
Should fix #2472

### CODE REVIEW

**Comment by kodermax** [comment]
When will it be published?

**Comment by kodermax** [comment]
What is the difficulty here?

**Comment by hideo54** [comment]
I can't wait for the release... I want to delete many ts-ignores in my code :sob:
It seems @xile611 has been busy recently. I hope they come back early :pray:

**Comment by hideo54** [comment]
It's finally released! Thank you 😍

**Pull request merged**
