### PR TITLE
Support keyboard navigation in pie chart

### PR DESCRIPTION
**Pull request by saghan**
Hi,

We are planning to use ReCharts in Microsoft Azure. We want to improve accessibility of the charts and contribute to this repository so that everyone using ReCharts can have a good experience.

This change is trying to enable users to navigate through pie chart using keyboard. [Web Content Accessibility Guidelines ](https://www.w3.org/WAI/WCAG21/Understanding/keyboard.html)suggests developers to add this ability to improve accessibility. If this change is accepted, Recharts users can navigate through pie chart using keyboard.

Since we use Enzyme+Cheerio in Recharts, which does not render test components in browser, I had to add dev-dependency on react testing library to test focus and navigation. This dependency will also help developers do a more thorough testing. Please let me know if you have any comments.

### CODE REVIEW

**Comment by saghan** [comment]
I am closing this due to branch issues

**Comment by cravend** [comment]
Will be unblocked by #2924

**Comment by mgifford** [comment]
@cravend issue https://github.com/recharts/recharts/pull/2924 was closed on August 2nd. Should this work? Should the test be re-run?

**Comment by saghan** [comment]
> 

I have pushed an empty commit to re-run the tests.

**Comment by ckifer** [comment]
Tests failing for JS doc issues, @saghan can you take a look?

**Comment by saghan** [comment]
> Tests failing for JS doc issues, @saghan can you take a look?

Done

**Review by semoal — APPROVED** [review]

**Review by ckifer — APPROVED** [review]

**Pull request merged**
