### PR TITLE
PR: Fix tooltip flickering #2143

### PR DESCRIPTION
**Pull request by simonhessner**
Fixes issue described in
- https://github.com/recharts/recharts/issues/2143
- https://github.com/recharts/recharts/issues/553
- https://github.com/recharts/recharts/issues/1220

The problem was that `CategoricalChartWrapper.createDefaultState(nextProps)` resets both `isTooltipActive` and `activeTooltipIndex` when the data of the chart changes. This is especially problematic in when the data is changed based on mouse events. In that case the tooltip disappears and appears again (flickering). Furthermore, the activeDot starts blinking. This PR fixes those problems.

I was not exactly sure if line 328 is necessary:
```
            ...keepFromPrevState, // TODO needed?
```

At least I did not notice a difference when removing the line. Should I remove it?

### CODE REVIEW

**Comment by Siedrix** [comment]
Is there any plan release date for this fix? It would be awesome to have in our app.

**Comment by simonhessner** [comment]
Maybe @arcthur can merge it into the master branch

**Comment by Siedrix** [comment]
If you guys need help testing it, let me know and I can dedicate some hours to this ticket.

**Comment by brandonparee** [comment]
I've done some testing with this fix and the main issue that I was facing is resolved. For me the tooltip was disappearing when the chart data was updated/the chart was rerendered. 

Now, there is one more issue to be resolved. If the chart data is updated, the tooltip payload needs to be updated as well. 

@simonhessner I have opened a PR in your fork to add some changes to resolve this.

**Comment by simonhessner** [comment]
@brandonparee Thanks! I am currently busy, but I'll look into it as soon as possible

**Comment by mauricioaznar** [comment]
Hello. I am having this issue as well. I disabled my tooltips until this is corrected. By the way, the library  is awesome, I love it <3.

**Comment by simonhessner** [comment]
I have tested and merged it. 

@mauricioaznar Please test if it works for you!

**Comment by simonhessner** [comment]
Awesome, thank you for merging!

**Comment by mauricioaznar** [comment]
I just tested it and it worked perfectly. Thank you very much.

**Comment by yelnar** [comment]
I would like to get this fix. Will it be released under `1.8.6` soon?

**Pull request merged**
