### PR TITLE
Fix issue 125 - wrong tick calculation

### PR DESCRIPTION
**Pull request by george-cz**

### CODE REVIEW

**Comment by xile611** [comment]
@george-cz 
The cause of this bug is that the value of `tick` in `Bar` locate in the left of each band, but the value of `tick` in `Line` locate in the middle of each band.

Your change may cause the bug of LineChart.

**Comment by george-cz** [comment]
You're right, I believe my latest commit fixed that. However the code isn't as pretty and straightforward anymore :D

**Comment by xile611** [comment]
Maybe it's better to fix `getTicksOfAxis`, I change this function in the latest version.

**Comment by xile611** [comment]
But, I find `getTicksOfAxis ` is in a mess.

**Comment by xile611** [comment]
@george-cz We think it's better to fix `getTicksOfAxis `, and we have fix it in V0.12.0. Thank you !

**Pull request closed without merging**
