### PR TITLE
fix: The box size of the Tooltip is 0 at the first rendering of TooltipBoundingBox

### PR DESCRIPTION
**Pull request by HHongSeungWoo**
## Description

When the size of the tooltip component changes, re-render the TooltipBoundingBox.

## Related Issue

#4424 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [ ] I have added a storybook story or extended an existing story to show my changes

### CODE REVIEW

**Comment by ckifer** [comment]
I thought the fix might be smaller than this 😅 

Appreciate the effort here, but if we change this here then we need to change it in 3.x as well - we don't want a regression later when people migrate major versions (even if this bug doesn't currently happen in 3.x). This seems snapper than what was currently being done..

**Comment by HHongSeungWoo** [comment]
Can fix the bug just by moving lastBoundingBox to state. It has been fixed that way in version 3.x as well.

**Comment by ckifer** [comment]
Yeah, could you do that here? We can use these other improvements on the 3.x branch and leave them out here just to prevent complicating things and diverging branches even further

**Comment by HHongSeungWoo** [comment]
I cannot cherry-pick the implementation from version 3.x, but it seems to be the minimal modification

**Review by ckifer — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
