### PR TITLE
YAxis reads context instead of cloning

### PR DESCRIPTION
**Pull request by PavelVanecek**
## Description

This time YAxis. Includes the fix from here: https://github.com/recharts/recharts/pull/4059

## Motivation and Context

Less cloning!

## How Has This Been Tested?

npm test, storybooks

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have added tests to cover my changes.
- [ ] I have added a storybook story or extended an existing story to show my changes
- [X] All new and existing tests passed.

### CODE REVIEW

**Review by ckifer — APPROVED** [review]
Sweeet!

**Comment by ckifer** [comment]
Looks like we got some diff https://www.chromatic.com/test?appId=63da8268a0da9970db6992aa&id=65a9a857f528248ad9c1cc81

**Comment by ckifer** [comment]
Only on two charts, but on those two the first YAxis tick dissapeared

**Comment by ckifer** [comment]
Seems like when we have two charts on the same page something changes @PavelVanecek

**Comment by PavelVanecek** [comment]
I wish we had these builds in branch checks, before merging

**Comment by ckifer** [comment]
Yeah me too... I can make an issue to try and do that

**Comment by ckifer** [comment]
https://github.com/recharts/recharts/issues/4063

**Pull request merged**
