### PR TITLE
Preserve JSDoc Comments

### PR DESCRIPTION
**Pull request by mxdvl**
## Description

By preserving comments, we enable better IDE integration and better documentation.

It’s worth noting that JSDocs type comments can be [automatically picked up by Storybook, too](https://storybook.js.org/docs/writing-docs).

## Related Issue

I could not find a specific issue, happy to open one for discussion if helpful.

## Motivation and Context

Currently, JSDoc comments are removed, which means that consumer have to use the online Docs to get more detailed information.

## How Has This Been Tested?

I’ve build the project locally and consumed it in my IDE of choice.

## Screenshots (if appropriate):

ticks information on hover in IDE

domain scale information on hover in IDE

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] I have added a storybook story or extended an existing story to show my changes

### CODE REVIEW

**Comment by mxdvl** [comment]
> I'm in support of this change but I'm afraid there won't be much useful information you can find in those comments 😞 it's a journey.

I think there’s a lot in there already! As a follow-up we could move or copy the information from the stories, too. I’d be happy to help where relevant as I think colocation of code and documentation is helpful.

**Comment by ckifer** [comment]
I'm cool with this too, especially since it's TS only which means bundle sizes don't increase or anything.  Let's do it

**Comment by mxdvl** [comment]
Any chance this will get released as v2.18?

**Comment by ckifer** [comment]
It will get released in 2.13 but I won't necessarily release it right now

**Comment by ckifer** [comment]
@mxdvl actually no. This PR went to the 3.x branch. You could make the same PR to master and it would get included in 2.13. This won't

**Pull request merged**
