### PR TITLE
remove role from Line

### PR DESCRIPTION
**Pull request by gcallaghan-nd**
## Description
Fix an ADA compliance issue by removing the image role from the line dots.

## Motivation and Context
Improves accessibility.

## How Has This Been Tested?
I ran the tests, and I also pulled up the storybook and ran the axeDevTools in Chrome to verify that the issue existed before my change, and did not exist after.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by rhuangabrielsantos — APPROVED** [review]

**Review by ckifer — APPROVED** [review]

**Comment by gcallaghan-nd** [comment]
@ckifer , I hate to be a pain, but I'm getting dinged by my ADA auditors for the issue solved by this PR. Is this fix coming out soon?

**Comment by ckifer** [comment]
I'm sorry but I really don't want to release the next minor version until this https://github.com/recharts/recharts/issues/3615#issuecomment-1653015251 is resolved and I don't have capacity to do a patch release just for this change. I don't have capacity to do much besides respond here tbh. 

I'll tell you what, if you:
* make a branch off of tag v2.7.2 
* only include this change
* include a patch version bump

I will review and publish as a patch version from that branch as soon as I can

**Comment by gcallaghan-nd** [comment]
Understood, I'm sure you're busy. Here's my new PR, I think I did what you asked: 
https://github.com/recharts/recharts/pull/3693

**Comment by ckifer** [comment]
https://www.npmjs.com/package/recharts/v/2.7.3

**Comment by gcallaghan-nd** [comment]
Thanks Coltin, I can't thank you enough!

**Pull request merged**
