### PR TITLE
ResponsiveContainer listen to parent element instead of the window

### LINKED ISSUE #104: ResponsiveContainer should respond to parent
I was checking `ResponsiveContainer` and I realised that it listens to the `window`'s resizing events instead of its parents resizing.

```js
// at src/component/ResponsiveContainer.js:31

window.addEventListener('resize', this.updateSizeOfWrapper);
```

To understand the consequence of that, imagine a dynamic dashboard interface where your users add new elements to it, changing the size of all the containers. We want the charts to change their sizes accordingly and not wait for a window resize, right?

What about having something that behave more or less like http://marcj.github.io/css-element-queries/ ?

### PR DESCRIPTION
**Pull request by zvictor**
fix #104

### CODE REVIEW

**Comment by xile611** [comment]
@zvictor How about the problem of initial width and height you have mentioned in [react-container-dimensions#1](https://github.com/okonet/react-container-dimensions/issues/1)

**Comment by zvictor** [comment]
I just analyzed it again and made a new PR there 🍻

**Comment by xile611** [comment]
Great! Thanks!

**Comment by okonet** [comment]
@zvictor I've merged it. Please test it with `master` before I'll cut the release if possible.

**Comment by zvictor** [comment]
@okonet I tried locally with `master` and it works fine.

**Comment by sbehrends** [comment]
Im having issues with the ResponsiveContainer. Not sure if related to same issues. 
Basically the container sticks to parent but recharts-surfcace element goes way of it's parent.
https://www.dropbox.com/s/0jpckmqfa6vdimt/Screenshot%202016-05-31%2004.39.50.png?dl=0

```
<ResponsiveContainer height={100}>
  <AreaChart data={Chardata}
        margin={{top: 10, right: 30, left: 0, bottom: 0}}>
    <Area type='monotone' dataKey='uv' stroke='#8884d8' fill='#8884d8' />
  </AreaChart>
</ResponsiveContainer>
```

**Comment by okonet** [comment]
@sbehrends try removing `margin`. This can be caused by CSS.

**Comment by sbehrends** [comment]
@okonet nope. The issue also occurred with a simpler example.
```
<ResponsiveContainer height={100}>
  <LineChart data={Chartdata}>
    <Line type='monotone' dataKey='pv' stroke='#8884d8' strokeWidth={2} />
  </LineChart>
</ResponsiveContainer>
```

**Comment by xile611** [comment]
@okonet  Can you show your complete code in JSFiddle?

**Comment by zvictor** [comment]
@xile611 closing a PR and pushing the changes as if it was your work is definitely not a good way to keep the community engaged in contributing to your project. Getting credits for my contribution is the only payment I expected to get for spending time publishing my changes.

**Comment by xile611** [comment]
@zvictor I apologize for my reckless behaviour, I should communicate with you if you are still willing to update the commits.

**Pull request closed without merging**
