### PR TITLE
upgrade react-resize-detector to v4

### PR DESCRIPTION
**Pull request by adi518**
This PR corresponds to #1659 and upgrades this dependency to latest version, which brings performance updates and more importantly, fixes [this](https://github.com/maslianok/react-resize-detector/issues/45) exception.

### CODE REVIEW

**Comment by maslianok** [comment]
Great!

As I said here https://github.com/recharts/recharts/issues/1659#issuecomment-554792094 `recharts` should use v4

**Comment by maslianok** [comment]
Thank you for your advice @adi518 
But the library wasn't "only patched". It was fully rewritten 2 times in order to improve performance, fix critical issues and deliver new features.

API remained backward compatible but I didn't want these versions to be auto-updated.
v4 was released more than 6 months ago and we have no major issues, so I can say that `recharts` should use the latest version

**Comment by adi518** [comment]
@xile611 Can you please merge this?

**Comment by avindra** [comment]
@adi518  It's updated already in the `2.0` branch https://github.com/recharts/recharts/commit/f82396a28cfa05195b1f3815f9bb923cb91420bd

`master` is still reflecting the `1.x` development which has been frozen / put on hold for 2.x efforts

**Comment by adi518** [comment]
I still think it should be merged. It's just a patch. Plus, v2 isn't released so waiting for that just to get this patch is an overhead.

**Comment by xile611** [comment]
Please try recharts@2.0.0-beta.0, recharts@2.0 Only support react@16 which has upgrade react-resize-detector to v4

**Comment by adi518** [comment]
But, what about breaking changes from v2 to v1? :-1:

**Pull request closed without merging**
