### PR TITLE
Scatter: activeShape should work with Tooltip

### PR DESCRIPTION
**Pull request by andrewangelle**
The existing `activeShape` prop on `<Scatter />` should work with the `<Tooltip />` in the same manner as `<Line />` and `<Bar />` do.

## Description

- #### src/chart/generateCategoricalChart.tsx
  - added a block to `getItemByXY` to set the find and set `activeIndex` when Tooltip is used with Scatter
  
- #### src/cartesian/Scatter.tsx
  - Refactored to use `<Shape />` instead of static method. 
  - Refactored to use `ActiveShape` type for `props.activeShape` and `props.shape`
  
- #### src/util/ActiveShapeUtils.tsx
  - Made `propTransformer` optional.
  - Added case to render a `<Symbols />` component
  
- #### test/chart/ScatterChart.spec.tsx
  - Added unit tests asserting on activeShape rendering with Tooltip
  
## Related Issue

#3794 
## Motivation and Context

To provide a consistent interface between Line / Bar / Funnel / RadialBar / Pie / Scatter and their respective props of activeDot / activeBar / activeShape

## How Has This Been Tested?

Unit tests and storybook

## Screenshots (if appropriate):
Screenshot 2023-10-06 at 10 03 07 AM

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] I have added a storybook story or extended an existing story to show my changes
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by nikolasrieble** [comment]
I will want to test this in a bit more detail, I remember that the Tooltip interaction for the Scatter was rather different to all other components (especially for handling multiple scatter points with the same xAxis value)

**Review by nikolasrieble — APPROVED** [review]
Great! I could not find any issue here. Thank you for your contribution! This is amazing.

**Comment by ckifer** [comment]
Does this not have a ton of overlap with https://github.com/recharts/recharts/pull/3818?

Could we process one at a time so we can view the diff without the overlap?

**Review by ckifer — CHANGES_REQUESTED** [review]
Same comments as on https://github.com/recharts/recharts/pull/3818, would maybe like to get one merged before the other

**Comment by andrewangelle** [comment]
@ckifer No problem. I'll close for now and re-open when the other gets merged.

**Pull request closed without merging**
