### PR TITLE
refactor: change `Symbols` to functional component

### PR DESCRIPTION
**Pull request by Yilun-Sun**
### TODO
- [ ] test plan

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by nikolasrieble** [comment]
Could you please add a test plan to this refactoring? If this is a breaking change, what is it breaking?

**Comment by ckifer** [comment]
@Yilun-Sun could you do a similar thing as @akamfoad did in https://github.com/recharts/recharts/pull/3479 and other refactor PRs? To compare the before and after diff with a component that uses `Symbols`?

**Review by akamfoad — APPROVED** [review]

**Comment by Yilun-Sun** [comment]
> @Yilun-Sun could you do a similar thing as @akamfoad did in #3479 and other refactor PRs? To compare the before and after diff with a component that uses `Symbols`?

Sure! I will do that!

**Comment by Yilun-Sun** [comment]
Before refactor:
截屏2023-06-03 00 19 23
After refactor:
截屏2023-06-03 00 19 05

Diff:
image

I built a tool that could compare two pictures online: https://pixel-match.netlify.com/

**Comment by ckifer** [comment]
Woah awesome!!

**Review by ckifer — APPROVED** [review]

**Pull request merged**
