### PR TITLE
fix: remove role attribute to bar layout

### PR DESCRIPTION
**Pull request by rhuangabrielsantos**
## Description
Only the bar chart has the role declared, as there is no aria-label for it, accessibility problems are occurring, this PR removes the role until the accessibility of all components is worked on

## Related Issue
https://github.com/recharts/recharts/issues/3449

## Screenshots (if appropriate):
Before:
image

After:
image

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by ckifer** [comment]
There are tests that rely on this role so they'll have to be fixed

**Comment by rhuangabrielsantos** [comment]
@ckifer 
I am not able to run the tests locally because of this error, but I believe that now it will go away, I copied the idea from `Line.spec.tsx` file

image

**Comment by ckifer** [comment]
We aren't using yarn, please use npm to install and that should resolve your issues

**Comment by rhuangabrielsantos** [comment]
It worked! Thanks!

**Review by nikolasrieble — APPROVED** [review]
🚀

**Pull request merged**
