### PR TITLE
The same Axis domain tests and storybook but for main branch

### PR DESCRIPTION
**Pull request by PavelVanecek**
This is exactly the same branch as here: https://github.com/recharts/recharts/pull/4613 and I want the storybook deployed on the website so that I can link to it.

### CODE REVIEW

**Review by ckifer — APPROVED** [review]
Cool - nice to have in both places while we work

**Comment by ckifer** [comment]
Oh wait I'm confused. This is still going to 3.x?

**Comment by PavelVanecek** [comment]
🤦

**Comment by PavelVanecek** [comment]
Yeah needs a rebase now. brb

**Comment by ckifer** [comment]
Hah no worries 😁

**Comment by PavelVanecek** [comment]
https://github.com/recharts/recharts/pull/4615

**Pull request closed without merging**
