### PR TITLE
chore: set includeEvent property in filterProps as required!

### PR DESCRIPTION
**Pull request by AnujSharma141**
`includeEvent` parameter of `filterProps` function in `ReactUtils.ts` which is of type `boolean` was set as optional which caused breaking events in components when not set.

## Motivation and Context

based on discussions from [#4056 ]

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] I have added a storybook story or extended an existing story to show my changes
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by PavelVanecek** [comment]
I'm a fan! Explicit parameters are better than implicit parameters.

However I wonder. What is the difference here? The only time the parameter is used is here https://github.com/recharts/recharts/blob/25528194d18be6b8907fc87750da395a547dc385/src/util/ReactUtils.ts#L297 as

```
(includeEvents && EventKeys.includes(key))
```

And when I try out this line of code, it turns out to work the same with `false` as it does with `undefined`:

image

What is the breaking change?

**Comment by AnujSharma141** [comment]
hi @PavelVanecek .. this change comes from a follow-up from a bug fix [#4056 ] that caused mouse events to not work in a component as `includeEvents` was missed to set `true` while using `filterProps`, so to avoid the same in future @ckifer and @nikolasrieble suggested to make the parameter non-optional. We want to make sure that the cases that requires `true` should not be left out here, cases with `false` and `undefined` will work same.

**Comment by ckifer** [comment]
@PavelVanecek there was no breaking change, this was just always broken. Making it required just requires us to set it so if it is intended to be there we don't miss it

**Review by ckifer — APPROVED** [review]
looks good!

**Pull request merged**
