### PR TITLE
test(JestMigration): convert YAxis

### PR DESCRIPTION
**Pull request by akib22**
## Description
Refactor `test/specs/cartesian/YAxisSpec.js` to `test-jest/cartesian/YAxis.spec.tsx`

## Related Issue
#3194  

## Types of changes
- Jest Migration

## Checklist:
- [x] My code follows the code style of this project.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by nikolasrieble** [comment]
This PR only removes the file and does not migrate it / or add a new file.

**Comment by proke03** [comment]
> This PR only removes the file and does not migrate it / or add a new file.

I think he kept the PR open to let people know he was working on it. But he seems to be working on another PR right now.

**Comment by akib22** [comment]
I started working on this issue, but I got confused by some test cases.
```ts
  it('Render 4 ticks', () => {
    const wrapper = mount(
      <AreaChart width={600} height={400} data={data}>
        <YAxis type="number" stroke="#ff7300" />
        <Area dataKey="uv" stroke="#ff7300" fill="#ff7300" />
      </AreaChart>,
    );
    const ticks = wrapper.find(Text);

    expect(ticks.length).to.equal(4);
    expect(ticks.first().props().y).to.equal(297.5);
  });
```
Why is `297.5` used in `expect(ticks.first().props().y).to.equal(297.5)` in this line?
In this test case, instead of using CSS class names to find elements, a React component (`const ticks = wrapper.find(Text);`) is used. I'm looking through the RTL documentation to see if it's possible. As a result, I am  late.

**Comment by nikolasrieble** [comment]
> I started working on this issue, but I got confused by some test cases.
> 
> ```ts
>   it('Render 4 ticks', () => {
>     const wrapper = mount(
>       <AreaChart width={600} height={400} data={data}>
>         <YAxis type="number" stroke="#ff7300" />
>         <Area dataKey="uv" stroke="#ff7300" fill="#ff7300" />
>       </AreaChart>,
>     );
>     const ticks = wrapper.find(Text);
> 
>     expect(ticks.length).to.equal(4);
>     expect(ticks.first().props().y).to.equal(297.5);
>   });
> ```
> 
> Why is `297.5` used in `expect(ticks.first().props().y).to.equal(297.5)` in this line? In this test case, instead of using CSS class names to find elements, a React component (`const ticks = wrapper.find(Text);`) is used. I'm looking through the RTL documentation to see if it's possible. As a result, I am late.

How about using https://testing-library.com/docs/example-findbytext/?

**Comment by akib22** [comment]
```ts
it('Render 1 ticks when domain={[0, 1000]} and dataKey is "noExist" ', () => {
    const wrapper = mount(
      <AreaChart width={600} height={400} data={data}>
        <YAxis stroke="#ff7300" domain={[0, 1000]} />
        <Area dataKey="noExist" stroke="#ff7300" fill="#ff7300" />
      </AreaChart>,
    );
    const ticks = wrapper.find(Text);

    expect(ticks.length).to.equal(4);
    expect(ticks.first().props().y).to.equal(297.5);
  });
```
I think this test case is wrong. When dataKey is "noExist" should not render any ticks but it's rendering ticks (` expect(ticks.length).to.equal(4);`). What do you think @nikolasrieble?

**Review by ckifer — APPROVED** [review]

**Comment by ckifer** [comment]
@akib22 - lets maybe follow up on that test to see what is going on. Since we're just migrating the current tests this should be ok

**Pull request merged**
