### PR TITLE
Fix legend size

### PR DESCRIPTION
**Pull request by zhonglin94**
## Description
The chart shrinks when I apply a scale on the chart container

## Related Issue
[The issue](https://github.com/recharts/recharts/issues/4246)

## Motivation and Context
The [legend size(height and width)](https://github.com/okonet/react-container-dimensions/issues/5) provided by the `getBoundingClientRect` is changed if it's parent container is transformed using scale. If the container scale is 3x, then the legend height is significantly larger than usual, which makes the chart content visibly smaller than expected.

## How Has This Been Tested?
Firstly, I tested locally using the Recharts demo
Then I build a package and test in a third party application that facing the same problem

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] I have added a storybook story or extended an existing story to show my changes
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by nikolasrieble — COMMENTED** [review]
Thank you for your contribution! This seems to be a great solution. Could you please add a test to make sure we do not break this feature again?

**Comment by zhonglin94** [comment]
> Thank you for your contribution! This seems to be a great solution. Could you please add a test to make sure we do not break this feature again?

Hi Nikolasrieble, I tried to add unit test but found it hard to propose a reasonable to test it. The [main reason](https://github.com/facebook/react/issues/4606) is that the `getBoundingClientRect` and `offsetHeight/offsetWidth` always return `0` in the jsdom.

**Comment by PavelVanecek** [comment]
Hello @zhonglin94 please see here for examples how to mock `getBoundingClientRect`: https://github.com/recharts/recharts/pull/4274/files

**Comment by zhonglin94** [comment]
> Hello @zhonglin94 please see here for examples how to mock `getBoundingClientRect`: https://github.com/recharts/recharts/pull/4274/files

Thank you so much for help. I add unit test to cover my changes.

**Comment by ckifer** [comment]
@PavelVanecek this change is targeting `master`. A lot of things just changed with Legend in the 3.x branch - I don't mind releasing this in a 2.x patch but this might get lost if it doesn't get added to 3.x now. Any suggestions?

**Comment by PavelVanecek** [comment]
Well we need another PR for 3.x. There will be conflicts. This is unfortunately the price for having two live branches.

**Comment by ckifer** [comment]
Ack, got it. I can port this to 3.x

**Review by ckifer — APPROVED** [review]
LGTM

**Comment by ckifer** [comment]
@zhonglin94 if you want to make the same PR to the 3.x branch feel free! Otherwise I'll get around to it eventually

**Pull request merged**
