### PR TITLE
fix: do not clear coordinate on item or chart leave

### PR DESCRIPTION
**Pull request by ckifer**
## Description

small fix for Redux tooltip animations

If we reset coordinate on every item and mouse out dispatch then we jarr the user when they hover again as the Tooltip always animates from the corner 0,0. This change keeps Tooltip animation the same as 2.x

## Related Issue

https://github.com/recharts/recharts/issues/4549

## Motivation and Context

Animations be the same that they are in 2.x. Also less stuttering/flying in from 0,0

## How Has This Been Tested?

- storybook

## Screenshots (if appropriate):
image

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] I have added a storybook story or extended an existing story to show my changes

### CODE REVIEW

**Comment by ckifer** [comment]
Ideally we probably just don't animate if we don't have a coordinate but

**Review by PavelVanecek — APPROVED** [review]
We should be able to have a test for this. Even if it's only on the selector level.

1. Start with empty coordinate
2. Mouse over - coordinate selector now returns
3. Mouse out - coordinate selector returns the last known coordinate

**Comment by ckifer** [comment]
Yeah agree - will add

**Comment by ckifer** [comment]
ok better!

**Review by PavelVanecek — APPROVED** [review]

**Pull request merged**
