### PR TITLE
fix(Brush): prevent resetting brush position unless start and end index are sent as props

### PR DESCRIPTION
**Pull request by ckifer**
## Description

Fix issue where brush snaps to points on the brush on click or on mouse out

This isn't perfect (see video), but its much better than it was. Not sure how to prevent this entirely...
But previously controlled brush barely worked so anything is an improvement.

## Related Issue

https://github.com/recharts/recharts/issues/4546

## How Has This Been Tested?

- all tests continue to pass
- tested in storybook

## Screenshots (if appropriate):

https://github.com/user-attachments/assets/99df72ff-4cb2-43b5-b4ec-0e73fac9b518

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] I have added a storybook story or extended an existing story to show my changes

### CODE REVIEW

**Comment by PavelVanecek** [comment]
Let's write tests for Brush! What are we missing?

**Comment by ckifer** [comment]
Time is always my excuse and then I end up spending more time figuring out the issue of course 😅. 

Tests needed:

* traveler does not reset after drag/mouseout/click - check when the value is changed and also when the traveler is dragged but not changed
* traveler does not reset after slide drag and mouse out/click
* controlled brush works as expected for all data indexes (0 to data.length - 1)

**Review by PavelVanecek — APPROVED** [review]
I'm a firm believer that `getDerivedStateFromProps` is not a good solution for anything but! If it's already there and it almost works then let's merge this. We can consider refactoring later if we find a roadblock.

**Comment by ckifer** [comment]
Oh I very much agree, it's just less cognitive load than a total refactor. Which I also did and has its issues 😆

**Pull request merged**
