### PR TITLE
XAxis uses scale (and domain and range) from redux instead of generator

### PR DESCRIPTION
**Pull request by PavelVanecek**
## Description

This breaks tooltip synchronisation and it will remain broken until that's moved to Redux store too. There is no visual diff though! https://www.chromatic.com/build?appId=63da8268a0da9970db6992aa&number=1129

## Related Issue

https://github.com/recharts/recharts/issues/4583

### CODE REVIEW

**Comment by PavelVanecek** [comment]
I may have missed the `reversed` prop. I will add more tests to the main branch before merging.

**Comment by ckifer** [comment]
Well I can fix the synchronization part! It's just not perfectly perfect

**Comment by PavelVanecek** [comment]
Yeah let's keep the sync for later PR.

**Comment by PavelVanecek** [comment]
Weird, this test works on my local but fails in CI. What's going on?

**Review by ckifer — APPROVED** [review]

**Comment by ckifer** [comment]
Looks like we have a few issues 
https://www.chromatic.com/build?appId=63da8268a0da9970db6992aa&number=1131

* composed bars are rendering on the Y Axis
* difference in ticks
* extendDomain/tick calculation isn't working for error bars (looks like this maybe wasn't working before either, not totally sure though)

**Comment by PavelVanecek** [comment]
ErrorBars domain never extended the X axis, only Y axis. I added that in the selector but apparently that alone was not good enough.

I'll look at the ticks.

**Comment by ckifer** [comment]
Oh huh, guess I'm thinking of reference elements

**Comment by PavelVanecek** [comment]
Okay interesting. The scatter is now actually _more correct_ because the axis domain takes into account the error bars. But unfortunately the ticks don't, and the graphical elements also don't. This might take a while to resolve.

Do you prefer to revert this change and get the storybook back to baseline, or keep it as "rejected" and roll forward?

**Pull request merged**
