### PR TITLE
fix: target supported node versions in CI

### PR DESCRIPTION
**Pull request by akamfoad**
## Description

Target only supported node versions, this includes 3 versions that are currently one of
- Maintained
- LTS
- Next
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] I have added a storybook story or extended an existing story to show my changes
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by HHongSeungWoo** [comment]
To run the test, you also need to downgrade the version of @testing-library/user-event.

**Comment by HHongSeungWoo** [comment]
recommmend ^13.5.0

**Comment by akamfoad** [comment]
@HHongSeungWoo What would be the reason for that?

**Comment by HHongSeungWoo** [comment]
Oh, the build succeeded. I had to create a new package-lock file because the build was failing due to the new syntax in TS. Seems like there were some dependency issues.

**Comment by akamfoad** [comment]
It was in fact due to dependency issue, I'm guessing it was from classnames, I'd mitigate that in a different PR, I have seen the warning for @types/classnames quite a few times now, looks like classnames is packing their types now.

Here is the fail in CI: https://github.com/recharts/recharts/actions/runs/6599091572/job/17927744175 

Thanks for the suggestion.

**Comment by akamfoad** [comment]
@PavelVanecek I removed the perf file since it was causing TypeChecking issues, it is not a big file and we have it in the history of the repo and I'm sure you have it locally too, we can add it back when we're confident that the performance tests work.

**Review by ckifer — APPROVED** [review]

**Comment by PavelVanecek** [comment]
@akamfoad yep that's fine, that's what git is for. We can always retrieve it from there later.

**Pull request merged**
