### PR TITLE
Replace classnames with clsx

### PR DESCRIPTION
**Pull request by wojtekmaj**
clsx is fully compatible with classnames API, is quickly gaining traction and is about 1/3rd smaller than classnames.

### CODE REVIEW

**Comment by wojtekmaj** [comment]
The chances of classnames being in the bundle is slightly higher indeed. But clsx is slowly closing the gap: https://npm-stat.com/charts.html?package=classnames&package=clsx

By migrating popular packages to the latter my hope was to speed up this trend.

**Comment by HHongSeungWoo** [comment]
@ckifer What do you think about this issue? It's faster, smaller, and doesn't require installing @types.

**Comment by ckifer** [comment]
Looks fine to me - though not having to install types isn't a huge benefit. 

It's a drop-in replacement so no concern from me

**Comment by wojtekmaj** [comment]
It's also now more popular than classnames: https://npmtrends.com/classnames-vs-clsx

**Comment by ckifer** [comment]
Merged!

**Pull request closed without merging**
