### PR TITLE
Add displayName for ResponsiveContainer

### PR DESCRIPTION
**Pull request by seiyab**
## Description
Add displayName for ResponsiveContainer

## Related Issue
N/A

## Motivation and Context
As of master branch, `<ResponsiveContainer />` is shown as anonymous component in React devtools.
`displayName` should help maintainer and application developer debugging.

And, to be honest, an application that I develop heavily depends on Recharts internal and removing name / displayName by `forwardRef` breaks our app 😅 .

## How Has This Been Tested?

I looked storybook and opened React devtools.
And I think new test for this change is not necessary.

## Screenshots (if appropriate):
image

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] ~My change requires a change to the documentation.~
- [ ] ~I have updated the documentation accordingly.~
- [ ] ~I have added tests to cover my changes.~
- [x] All ~new and~ existing tests passed.

### CODE REVIEW

**Comment by seiyab** [comment]
ResponsiveContainer looks to be shown as `"ResponsiveContainer"` in Storybook on master branch, too.
I'm misunderstanding something.
I made it draft.

**Comment by ckifer** [comment]
static `displayName` is used for debugging purposes and shouldn't have anything to do with how devtools interprets the component name itself (at least not that I know of). Unfortunately `displayName` was used in implementation of recharts but shouldn't break anything here

**Comment by seiyab** [comment]
Thank you, I understand🙌.
https://legacy.reactjs.org/docs/react-component.html#displayname

Anyway, it should be better to have a displayName here.

**Comment by ckifer** [comment]
I would say that this is a deprecated attribute since it isn't in the current react docs at all. 

"Usually, you don’t need to set it explicitly because it’s inferred from the name of the function or class that defines the component"

So I don't think this PR is needed, if anything we should be removing displayName from the codebase

**Comment by ckifer** [comment]
Going to close this as won't fix as this would be moving recharts backwards. I think instead we could fix it like some of the things suggested here https://stackoverflow.com/a/71692429/8050147

**Comment by seiyab** [comment]
Sorry for late response.
Closing this PR is OK because I'm not eager to merge it.

I'm still investigating personally because I'm still getting confused about devtools on Recharts document shows `Anonymous`, neither desired name `ResponsiveContainer` nor minified name like `t` for `ResonsiveContainer`.
image

**Pull request closed without merging**
