### PR TITLE
Storybook: Add BarInBar story

### PR DESCRIPTION
**Pull request by nikolasrieble**
## Description
Answering a request on SO https://stackoverflow.com/questions/75401714/is-it-possible-to-stack-2-bars-layer-on-top-of-each-other-not-above-each-other

## Screenshots (if appropriate):
Screenshot 2023-02-14 at 22 42 17

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by proke03 — COMMENTED** [review]
Looks good.
But I don't know if this type of bar chart is used enough to be added as a story.
If we need to compare multiple values, it seems more common to put the bars side by side like below without overlapping.
column-chart-excel

**Comment by ckifer** [comment]
Yeah +1, the SOF use-case is very niche

**Comment by nikolasrieble** [comment]
> Looks good. But I don't know if this type of bar chart is used enough to be added as a story. If we need to compare multiple values, it seems more common to put the bars side by side like below without overlapping. column-chart-excel

I agree, one could argue this belongs into examples more than into the API folder, being an edge case. Should I move it there?

**Comment by proke03** [comment]
If you move to an example, how about changing the example data to be closer to the real example like the data representing the achievement of the target number.

**Pull request merged**
