### PR TITLE
Update Bar.tsx label type definition

### PR DESCRIPTION
**Pull request by nimo-juice**
Fixing the bar label type definition, inline with how its defined in other places.

### CODE REVIEW

**Comment by nimo-juice** [comment]
@semoal any thoughts? :)

**Review by semoal — APPROVED** [review]

**Comment by semoal** [comment]
LGTM

**Comment by nimo-juice** [comment]
@semoal <3 thank you! How can we get this merged / deployed? :)

**Comment by nimo-juice** [comment]
Maybe @xile611 can help? :)

**Pull request merged**
