### PR TITLE
refactor: `Cross` to component function

### PR DESCRIPTION
**Pull request by akamfoad**
## Description

Refactor `Cross` component from class to function component.

## Motivation and Context

Refactoring library to be more maintainable - testing refactor-ability

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [X] All new and existing tests passed.

### CODE REVIEW

**Comment by nikolasrieble** [comment]
Love it! Can you please test by adding a storybook story that uses the Cross component? 
Or a unit test with RTL doing so? 

Same please for all other refactorings. We need to be confident that this does not break anything. And manual testing is not promising 😓

**Comment by akamfoad** [comment]
@nikolasrieble Sure, the current tests are passing which means the current tested behavior worked as expected, I don't think most of the refactors will have any UI changes as I try to avoid that. I'll try to add jest test cases for the functions and codes that are refactored out of the components.

**Comment by akamfoad** [comment]
@nikolasrieble 

As I see, snapshots are best strategy for these small components, making sure their result is consistent when changes happen. Let me know if you'd have a different approach, I updated all other PRs too.

**Comment by nikolasrieble** [comment]
> @nikolasrieble
> 
> As I see, snapshots are best strategy for these small components, making sure their result is consistent when changes happen. Let me know if you'd have a different approach, I updated all other PRs too.

I think storybook is best, because we then can with chromatic visually compare whether the behaviour is identical.

**Comment by akamfoad** [comment]
@nikolasrieble I'd have added a storybook for it too but since these components don't have storybooks it will not make any difference to add it in this PR tbh. But I can add some storybook entries for these shapes in a different one.

**Comment by nikolasrieble** [comment]
see https://github.com/recharts/recharts/pull/3539

**Comment by akamfoad** [comment]
@nikolasrieble The build broke due to some special characters in `Cross` story, I fixed those as well, I think now we can be confident to merge this. I'm working on adding a similar story to other Components I refactored so we can have a story before merging the refactor PRs.

**Comment by ckifer** [comment]
@akamfoad fixing the build issue separately from this PR since it is unrelated, you may have to reconcile that change after I merge https://github.com/recharts/recharts/pull/3543

**Comment by akamfoad** [comment]
@ckifer Sure I'll

**Comment by akamfoad** [comment]
@nikolasrieble  @ckifer 

I noticed that the Chromatic action will run only on master pushes (I guess) but not on PRs, does that mean these PRs should be merged then tested whether they're correct or not, or am I missing something?

https://github.com/recharts/recharts/blob/a32f1ee85ecae4ccf18cd3352f164a707c737f03/.github/workflows/chromatic.yml#L6-L7

**Comment by akamfoad** [comment]
Makes sense, I'd be happy to help where I can. I'd love to see progress on this project.

**Review by nikolasrieble — APPROVED** [review]
Tested manually and works well in storybook. Thank you for your contribution, and please excuse the very slow reaction time on our side ❤️

**Pull request merged**
