### PR TITLE
feat(Sankey): add prop to control sankey sorting

### PR DESCRIPTION
**Pull request by daformat**
This PR adds a prop to the Sankey component to allow disabling the y sorting

## Description

The Sankey component sorts nodes by y value and doesn't expose a way to control this behavior. This PR adds a boolean prop that allow to disable that sorting behavior. This prop default to true so that existing implementation keep rendering the same.

Here's a visual to showcase the current behavior and the new one with the prop set to false:

With sorting | Without sorting
--|--
image | image

The storybook has been updated to reflect the new prop

## Related Issue

#3683

## Motivation and Context

When using Sankey charts to create cashflow charts, we want to group expenses or income by category. The automatic sorting makes chart links overlap and cross each other, when we want to actually group things by topic to keep the cashflow analysis legible. The fact that one expense in one category is smaller than others in other categories shouldn't move the link around and mix it with other categories, as it makes the chart more complicated to read. The goal is to give control to the user on the grouping of the branches, while still providing with the option to sort data by default for backward compatibility

## How Has This Been Tested?

- [x] used the prop on a existing implementation
- [x] manually tested through storybook
- [x] ran the jest test suites
- [x] ran the storybook tests  

## Screenshots (if appropriate):

See description

## Types of changes

- ~[ ] Bug fix (non-breaking change which fixes an issue)~
- [x] New feature (non-breaking change which adds functionality)
- ~[ ] Breaking change (fix or feature that would cause existing functionality to change)~

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly. (https://github.com/recharts/recharts.org/pull/275)
- ~[ ] I have added tests to cover my changes.~ (I don't see how I can automatically test this since no data-attributes are present on the nodes / links and the existing Sankey test are just counting nodes)
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by ckifer — APPROVED** [review]
LGTM, will wait another review though

**Review by akamfoad — APPROVED** [review]
Looks good to me

**Comment by akamfoad** [comment]
NIT: @daformat I'd love to see the example in the PR description as a storybook story, more complex and real-world stories with more data helps spot differences and bugs easier.

**Comment by ckifer** [comment]
+1 to that for sure

**Comment by daformat** [comment]
@akamfoad done! I've added the CustomNodeAndLink the the API stories

**Review by akamfoad — APPROVED** [review]
Thanks, good work @daformat
looks good to me.

**Review by ckifer — APPROVED** [review]

**Pull request merged**
