### PR TITLE
fix(polar): set paddingAngle 0 when pie data length <= 1

### PR DESCRIPTION
**Pull request by syi0808**
# Set paddingAngle 0 when pie data length <= 1

## Description
If datas length is less or equal then 1 in props, set force paddingAngle to 0.

## Motivation and Context
In my project using recharts's pie chart. I expected that setting paddingAngle would not create a gap when there was 1 data, but it did not.
According to https://recharts.org/en-US/api/Pie#paddingAngle. paddingAngle is "The angle between two sectors.", So when there was just 1 data, it should not create gap.

## How Has This Been Tested?
recharts has no e2e test. So i tested on storybook.

### before
Screenshot 2024-07-04 at 9 39 34 PM
### after
Screenshot 2024-07-04 at 9 53 51 PM

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [ ] I have added a storybook story or extended an existing story to show my changes

### CODE REVIEW

**Comment by ckifer** [comment]
I think the title is wrong? <= 1 right? Looks like the code is correct

**Review by ckifer — COMMENTED** [review]
Makes sense to me. Could we add a unit test?

**Comment by syi0808** [comment]
> Makes sense to me. Could we add a unit test?

sorry to make confuse you. I have trouble to writing test.
We can't access rendered component's state, so I have one idea. test to snapshot from rendered path element in pie component. Would that be a good way?

**Comment by ckifer** [comment]
Snapshot tests aren't generally a good idea, nor are testing internal state. 

What you can do is render the pie test that the it does not look like it did previously. Find the element, find the path attribute, asset on that

**Comment by syi0808** [comment]
In rechart latest version, when set paddingAngle to 360, path element disappeared.
So i tested if path is rendered when setting data.length to 1 and paddingAngle to 360.

**Comment by ckifer** [comment]
That works. As long as it was failing before the change and is passing after. 

Will potentially help prevent future regressions

**Comment by syi0808** [comment]
force push just remove test.only syntax.

**Review by ckifer — APPROVED** [review]
LGTM as long as it passes CI

**Comment by ckifer** [comment]
Thank you

**Pull request merged**
