### PR TITLE
Show tooltip on chart focus

### PR DESCRIPTION
**Pull request by PavelVanecek**
## Description

Let's start adding keyboard controls back.

## Related Issue

https://github.com/recharts/recharts/issues/4549

### CODE REVIEW

**Comment by ckifer** [comment]
Oops, other PR made conflicts

**Comment by PavelVanecek** [comment]
I will fix tomorrow

**Review by ckifer — APPROVED** [review]
LGTM otherwise 🚀

**Comment by ckifer** [comment]
easy conflicts so I resolved

**Pull request merged**
