### PR TITLE
Storybook: Add docs for CartesianAxis

### PR DESCRIPTION
**Pull request by petii**
## Description
Adds an MDX file for CartesianAxis.
 - [ ] TODO: document/categorize properties

## Related Issue
https://github.com/recharts/recharts/issues/2476

## Motivation and Context
Some written text could be useful 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by ckifer** [comment]
@petii @nikolasrieble are we going to add this or no?

**Comment by petii** [comment]
@ckifer I can certainly try and pick this back up. Free time wasn't as plentiful as I would've liked in the recent months.

**Comment by ckifer** [comment]
I feel you there, no worries at all

**Comment by ckifer** [comment]
PR is stale so closing this for now - feel free to open back up whenever time allows

**Pull request closed without merging**
