### PR TITLE
Typos

### PR DESCRIPTION
**Pull request by sharma-shray**
## Description
Minor typos fixes 

## Motivation and Context
Improve readability

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] I have added a storybook story or extended an existing story to show my changes

### CODE REVIEW

**Review by ckifer — CHANGES_REQUESTED** [review]
Can you make the typo fixes without adding the log statement? It doesn't need to be there (and it isn't refactoring)

Also please fill out the PR template as to why you are doing this.

**Comment by sharma-shray** [comment]
> Can you make the typo fixes without adding the log statement? It doesn't need to be there (and it isn't refactoring)
> 
> Also please fill out the PR template as to why you are doing this.

Thanks for the response, fixed

**Comment by ckifer** [comment]
The build is failing, you need to fix the linter errors

**Comment by ckifer** [comment]
@sharma-shray can you fix the build?

**Comment by ckifer** [comment]
Going to close this due to no response

**Pull request closed without merging**
