### PR TITLE
Added the className in the Payload Interface

### PR DESCRIPTION
**Pull request by Nikhilh26**
## Description

Added Optional className in the Payload Interface
#4050 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] I have added a storybook story or extended an existing story to show my changes
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by ckifer — CHANGES_REQUESTED** [review]
The only change here is the lock file. I think maybe you meant to commit something else?

**Comment by Nikhilh26** [comment]
Yeah wait i will correct that . i was just asking if i add className as optional property in Payload interface will that work?

**Comment by ckifer** [comment]
Yep, it's just the type that's missing

**Comment by ckifer** [comment]
Closing this because of the other PR

**Pull request closed without merging**
